%% Problem 2 
% Each new term in the Fibonacci sequence is generated by adding the 
% previous two terms. By starting with 1 and 2, the first 10 terms will be:
% 
% 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
% 
% By considering the terms in the Fibonacci sequence whose values do not 
% exceed four million, find the sum of the even-valued terms.

F1 = 1;
F2 = 2;
F3 = 0;
count = 0;
sum = 2;
while F3 <= 4e6
    F3 = F2 + F1;
    if mod(F3,2) == 0
        sum = sum + F3;
    end
    F1 = F2;
    F2 = F3;
end
display(['The sum of even Fibonacci elements less than 4 million is ' ...
        num2str(sum)])